### ISSUE TITLE
platform-version is incompatible with admin-ui-classic-bundle

### ISSUE THREAD

**Issue by ghost** [pimcore/platform-version#26]
### Description

Whith Pimcore 11 when installing latest version of pimcore/platform-version we get an error saying that pimcore/platform-version conflicts with pimcore/admin-ui-classic-bundle (see attached screenshot).

### How to reproduce

- [ ] Install last Pimcore 11
- [ ] Run composer require pimcore/platform-version:^2023.1
![image](https://github.com/pimcore/platform-version/assets/150000890/7dcddb67-66cc-44b4-9d38-11f983e2c439)

**Comment by fashxp** [comment]
original problem probably was, that skeleton required `"pimcore/admin-ui-classic-bundle": "^1.2"`, see  https://github.com/pimcore/skeleton/blob/11.x/composer.json#L16

**Comment by fashxp** [comment]
with platform release 2023.3 that will be fixed anyway
